services:
  gateway.webapi:
    image: gateway.webapi
    container_name: AuxoniaVault.GatewayApi
    build:
      context: .
      dockerfile: src/gateway/Gateway.WebApi/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000;